# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 11 Jan 2021 13:09:44 +0000
*	@ALL	8
売上ガイド	@group1	1
ポイントガイド	@group2	2
売上ガイド	orange	2
wiki:藤田サイト	@group1	1
