<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: grape
 * Date: Mon, 11 Jan 2021 15:08:31 +0000
 */

$conf['title'] = 'クレディWIKI';
$conf['lang'] = 'ja';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
