# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 11 Jan 2021 13:09:44 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

orange:$2y$10$QcGuBJmFu73xmX4L9tDkheKIUqSUlw4LSWlK51YsoUwnRLKo1JPiu:ryota asakura:takashi.shioya8@gmail.com:group1
grape:$2y$10$Oth6a5w0cZSIDVzfZiwB1O5hbZvankXMTZTJyj4CWZHz7deFmilai:takashi shioya:honolua38@gmail.com:admin,user,group2
